module.exports=
[
    {
        username:"ptaylan",
        id:1,
        firstName:"Pınar",
        lastName:"Taylan",
        phone:"0123456789",
        email:"pinartaylan07@gmail.com"
    },
    {
        username:"bozeren",
        id:2,
        firstName:"Beyza",
        lastName:"Ozeren",
        phone:"0987654321",
        email:"bozeren@gmail.com"
    },
    {
        username:"eaydogan",
        id:3,
        firstName:"Esra",
        lastName:"Aydoğan",
        phone:"1367908534",
        email:"eaydogan@gmail.com"
    },
    {
        username:"galiyeva",
        id:4,
        firstName:"Gülnar",
        lastName:"Aliyeva",
        phone:"3298590453",
        email:"galiyeva@gmail.com"
    }
];